name: Release Container

on:
  workflow_run:
    workflows:
        - Increment Tagged Version
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Build image
        run: docker buildx build -t ${{ github.event.repository.name }} --file ./Dockerfile . --platform linux/amd64 --load
      - name: Test image
        run: docker run -i ${{ github.event.repository.name }}
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image tags
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]') # This changes all uppercase characters to lowercase.
          SEMVER_TAG=$(git tag --points-at HEAD | tail -n 1)
          LATEST_TAG=latest
          echo IMAGE_ID=$IMAGE_ID
          echo SEMVER_TAG=$SEMVER_TAG
          echo LATEST_TAG=$LATEST_TAG
          docker tag ${{ github.event.repository.name }} $IMAGE_ID:$SEMVER_TAG
          docker push $IMAGE_ID:$SEMVER_TAG
          docker tag ${{ github.event.repository.name }} $IMAGE_ID:$LATEST_TAG
          docker push $IMAGE_ID:$LATEST_TAG
      - name: Cleanup Untagged
        uses: dylanratcliffe/delete-untagged-containers@v1.2.3
        with:
          package_name: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
